name = "Test Pack"
author = "LutfilahDz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bce7eccb567ac1d322cf102d291c41501aba346509c5d3d1b8aff68013700314"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
