name = "Test Pack"
author = "LutfilahDz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26b171c93909cec224dc508b4859091964601746be53439c18d70a407997ad0e"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
unsup = "1.1.3"

[options]
datapack-folder = "world/datapacks"
