name = "Test Pack"
author = "LutfilahDz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9a66007887633e9a1b8293a9a48b32ab3144e5cc52d4ab3bc1f6428d73cda02"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
unsup = "1.1.3"

[options]
datapack-folder = "world/datapacks"
