name = "Test Pack"
author = "LutfilahDz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4f539b451136bf06ed4863a6146ae0a2055fe33e65ee66fd3e52b914df06e3a"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
