name = "Test Pack"
author = "LutfilahDz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4e2cef9ab7977d1cf1e9c559a7398ff3ff438d8da78d009b41e691f081ccc32"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
