name = "Test Pack"
author = "LutfilahDz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5beec44552a40bd9994e2734ee190f75a7c034240fa1c7748f99b1766e70d7e6"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
