name = "Test Pack"
author = "LutfilahDz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c248a595696787e3e8980bc13077b470bde93d48c5ba195a930d9dce4906746b"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
unsup = "1.1.3"

[options]
datapack-folder = "world/datapacks"
