[flavor_groups.version]
name = "Mod Package"
description = "Choose the mod package that best suits your needs in Sekai Survival.\nEach package is designed to enhance your gaming experience with different levels of optimization and features."
side = "both"
[[flavor_groups.version.choices]]
id = "complete_package"
name = "Complete"
description = "Complete package with optimization and additional quality of life features for the best gaming experience.\nJust install and play without any hassle!"
[[flavor_groups.version.choices]]
id = "performance_package"
name = "Performance"
description = "Basic package enhanced with performance-focused mods.\nPerfect for players who don't have their own optimization mods."
[[flavor_groups.version.choices]]
id = "basic_package"
name = "Basic"
description = "Basic essential mods required for server compatibility.\nIdeal for players who already have their own additional mods."

[flavor_groups.rendering]
name = "Rendering"
description = "Choose your rendering setup. Sodium is a modern rendering engine that greatly improves performance. Iris allows you to use shaders for enhanced visual effects."
side = "client"
[[flavor_groups.rendering.choices]]
id = "rendering_off"
name = "None"
description = "No rendering enhancements"
[[flavor_groups.rendering.choices]]
id = "rendering_sodium"
name = "Sodium Only"
description = "Performance optimization with Sodium and additional features like improved graphics settings and visual tweaks."
[[flavor_groups.rendering.choices]]
id = "rendering_iris"
name = "Sodium + Iris Shaders"
description = "Full performance optimization suite with Sodium and its addons, plus shader support through Iris for enhanced visual effects"

[flavor_groups.xaero]
name = "Xaero's Maps"
description = "Choose whether to use Xaero's Minimap and World Map, providing detailed navigation and map features for better exploration."
side = "client"
choices = ["xaero_off", "xaero_on"]

[flavor_groups.distant_horizons]
name = "Distant Horizons"
description = "Choose whether to enable Distant Horizons, a mod that renders distant terrain for better view distances with minimal performance impact."
side = "client"
choices = ["distant_horizons_off", "distant_horizons_on"]

[metafile.sodium]
flavors = ["sodium_on"]
[metafile.indium]
flavors = ["iris", "sodium"]
[metafile.iris]
flavors = "iris"
[metafile.canvas]
flavors = "canvas"
