[flavor_groups.flavor]
name = "Flavor"
description = "How do you want to play Rewind Upsilon?"
side = "both"
[[flavor_groups.flavor.choices]]
id = "standard"
name = "Standard"
description = "You want to create a new world with normal terrain generation, or join a server using this flavor.<ul><li>PowerConverters disabled</li><li>All ExtraBiomesXL biomes enabled</li></ul>"
[[flavor_groups.flavor.choices]]
id = "compatible"
name = "Compatible"
description = "You want to load an existing FTB Ultimate world and continue where you left off, or join a server using this flavor.<ul><li>PowerConverters enabled</li><li>Same biomes as FTB Ultimate</li></ul>\n\n<b>Warning: This has not been thoroughly tested!</b> Always keep backups!"
[[flavor_groups.flavor.choices]]
id = "skyblock"
name = "Skyblock"
description = "You want to create a new world with Emi's 1.4.7 skyblock challenge, or join a server using this flavor.\n<ul><li>PowerConverters disabled</li><li>Emi's Skyblock enabled</li></ul><b>Emi's skyblock challenge is <i>very hard</i>.</b> You will need an intimate familiarity with the mods and judicious use of NEI to get anywhere.\n\n<i>Hint:</i> You can get drones from Scrapboxes, and Alveary Swarmer princesses <i>will not</i> die."

[flavor_groups.minimap]
name = "Minimap"
description = "Which minimap mod do you want?"
side = "client"
[[flavor_groups.minimap.choices]]
id = "reis_minimap"
name = "Rei's Minimap"
description = "Use Rei's Minimap. This was removed from FTB packs at the time due to it exposing the IP of private servers in YouTube videos, but in general is a very good mod."
[[flavor_groups.minimap.choices]]
id = "voxelmap"
name = "VoxelMap"
description = "Use VoxelMap. This is the mod that was included in FTB Ultimate, but it's a little janky and has fewer features than Rei's.\n\n<i>Requires LiteLoader. NiteLoader will be installed.</i>"

[flavor_groups.music]
name = "Menu Music"
description = "What menu music do you want?"
side = "client"
[[flavor_groups.music.choices]]
id = "music_upsilon"
name = "Upsilon"
description = "Use CC-licensed happy chiptunes chosen by the Rewind project, created by xyce and radix."
[[flavor_groups.music.choices]]
id = "music_voxel"
name = "Classic"
description = "FelixMoog's nostalgic covers of Call Me Maybe, Pirates of the Caribbean, Discord, and We Didn't Start The Fire, same as FTB Ultimate and VoxelBox.\n\n<i><b>Potentially a copyright hazard due to reused melodies</b> — not recommended for streamers.</i>"

[metafile.extrabiomes-standard]
flavors = ["standard", "skyblock"]
[metafile.extrabiomes-ultimatecompat]
flavors = "compatible"
[metafile.powerconverters]
flavors = "compatible"
[metafile.ultimateskyblock]
flavors = "skyblock"
[metafile.overworld-2]
flavors = "standard"

[metafile.reiminimap]
flavors = "reis_minimap"

[metafile.niteloader]
flavors = "voxelmap"
[metafile.voxelmap]
flavors = "voxelmap"

[metafile.felixmoog-discord]
flavors = "music_voxel"
[metafile.felixmoog-fire]
flavors = "music_voxel"
[metafile.felixmoog-maybe]
flavors = "music_voxel"
[metafile.felixmoog-pirates]
flavors = "music_voxel"

[metafile.xyceradix-mosaik]
flavors = "music_upsilon"
[metafile.xyceradix-nova]
flavors = "music_upsilon"
[metafile.xyceradix-rainbowdash]
flavors = "music_upsilon"

[metafile.dartcraft-zs]
flavors = "dartcraft_on"

[flavor_groups.version]
name = "Mod Package"
description = "Choose which mod package suits your needs for playing Sekai Survival"
side = "both"
[[flavor_groups.version.choices]]
id = "full_version"
name = "Complete"
description = "All features included! Contains optimization mods for better performance plus quality of life mods like map (Xaero), item search (JEI), block info (Jade), zoom, and more. Recommended for single player or if server allows these mods."
[[flavor_groups.version.choices]]
id = "optimized_version"
name = "Performance"
description = "Focuses on game performance with mods like Entity Culling, Ferrite Core, and Modern Fix. Perfect balance between features and performance."
[[flavor_groups.version.choices]]
id = "standard_version"
name = "Basic"
description = "Basic essential mods for server compatibility. Perfect for joining servers that require minimal mods. Most lightweight option."

[flavor_groups.hard_mode]
name = "Hard Mode"
side = "both"
choices = ["hard_mode_off", "hard_mode_on"]

[metafile.sodium]
flavors = ["iris", "sodium"]
[metafile.indium]
flavors = ["iris", "sodium"]
[metafile.iris]
flavors = "iris"
[metafile.canvas]
flavors = "canvas"
