[flavor_groups.version]
name = "Mod Package"
description = "Choose the mod package that best suits your needs in Sekai Survival.\nEach package is designed to enhance your gaming experience with different levels of optimization and features.\n\n"
side = "both"
[[flavor_groups.version.choices]]
id = "complete_package"
name = "Complete"
description = "Complete package with optimization and additional quality of life features for the best gaming experience.\nJust install and play without any hassle!"
[[flavor_groups.version.choices]]
id = "performance_package"
name = "Performance"
description = "Basic package enhanced with performance-focused mods.\nPerfect for players who don't have their own optimization mods."
[[flavor_groups.version.choices]]
id = "basic_package"
name = "Basic"
description = "Basic essential mods required for server compatibility.\nIdeal for players who already have their own additional mods."

[flavor_groups.sodium]
name = "Sodium"
description = "Choose whether to use Sodium, a high-performance rendering engine that significantly improves FPS."
side = "client"
choices = ["sodium_off", "sodium_on"]

[flavor_groups.iris]
name = "Iris Shaders"
description = "Choose whether to use Iris Shaders, a mod that allows you to use OptiFine shaders with Sodium for enhanced visual effects."
side = "client"
choices = ["iris_off", "iris_on"]

[flavor_groups.distant_horizons]
name = "Distant Horizons"
description = "Choose whether to enable Distant Horizons, a mod that renders distant terrain for better view distances with minimal performance impact."
side = "client"
choices = ["distant_horizons_off", "distant_horizons_on"]

[metafile.sodium]
flavors = ["sodium_on"]
[metafile.indium]
flavors = ["iris", "sodium"]
[metafile.iris]
flavors = "iris"
[metafile.canvas]
flavors = "canvas"
