[flavor_groups.version]
name = "Mod Package"
description = "Choose which mod package suits your needs for playing Sekai Survival"
side = "both"
[[flavor_groups.version.choices]]
id = "complete_package"
name = "Complete"
description = "All features included! Contains optimization mods for better performance plus quality of life mods like map (Xaero), item search (JEI), block info (Jade), zoom, and more. Recommended for single player or if server allows these mods."
[[flavor_groups.version.choices]]
id = "performance_package"
name = "Performance"
description = "Focuses on game performance with mods like Entity Culling, Ferrite Core, and Modern Fix. Perfect balance between features and performance."
[[flavor_groups.version.choices]]
id = "basic_package"
name = "Basic"
description = "Basic essential mods for server compatibility. Perfect for joining servers that require minimal mods. Most lightweight option."

[flavor_groups.sodium]
name = "Sodium"
side = "client"
choices = ["sodium_off", "sodium_on"]

[flavor_groups.distant_horizons]
name = "Distant Horizons"
side = "client"
choices = ["distant_horizons_off", "distant_horizons_on"]

[metafile.sodium]
flavors = ["sodium_on"]
[metafile.indium]
flavors = ["iris", "sodium"]
[metafile.iris]
flavors = "iris"
[metafile.canvas]
flavors = "canvas"
