name: Deploy packwiz pack to GitHub Pages

on:
  push:
    branches: ["main", "dev"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [main, dev]
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Checkout ${{ matrix.branch }}
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact for ${{ matrix.branch }}
        id: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: pack/

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
        with:
          artifact_id: ${{ steps.upload.outputs.artifact_id }}
