name: Deploy packwiz pack to GitHub Pages

on:
  push:
    branches: ["main", "dev"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [main, dev]
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      # 1) Checkout branch target (default shallow clone fetch-depth:1)
      - name: Checkout ${{ matrix.branch }}
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      # 2) Aktifkan GitHub Pages (membuat deployment context)
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      # 3) Upload artifact dengan nama unik per branch
      - name: Upload Pages artifact for ${{ matrix.branch }}
        id: upload
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages-${{ matrix.branch }}          # Dinamis per branch :contentReference[oaicite:2]{index=2}
          path: pack/

      # 4) Deploy menggunakan nama artifact yang sama
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages-${{ matrix.branch }}  # Harus cocok dengan 'name' di upload :contentReference[oaicite:3]{index=3}
